### ISSUE TITLE
Integrate Metallicity_Stack_Commons in general

### ISSUE THREAD

**Issue by astrochun** [rafia37/Evolution-of-Galaxies#2]
Changes to implement:

Refactoring:
1. Import `get_user` to replace `getuser()`
2. Import `dir_date` to replace `get_time`
3. Import `fitting_lines_dict` to replace `lambda0`, `line_type`, and `line_name`
4. Import `k_dict` to replace `k_4363` and `k_5007`
5. Import `attenuation` to replace `dust_attenuation`

**Comment by astrochun** [comment]
Changes implemented by @cmccormick1  in ba32ac9 and has been tested.

**Comment by cmccormick1** [comment]
Testing Done:
1. Visual check of directories/files being created to make sure they are the same as before.
