### ISSUE TITLE
Bug: Incorrect curve fitting for metallicity vs mass individual plot

### ISSUE THREAD

**Issue by cmccormick1** [rafia37/Evolution-of-Galaxies#32]
After plotting functions were reorganized, the curve fit for composite measurements on the individual metallicity vs mass plot differed from past plots.

**Comment by cmccormick1** [comment]
Only some of the revised emission line "Flux_Gaussian" values differ slightly in the "emission_line_fit.revised.tbl" table, and only detection bins differ. ("Flux_Observed" values are the same)

Two runs compared:
"MZEvolve/massbin/03272020/75_112_113_300_600_1444_1443errbar_test11"
"MZEvolve/massbin/05192020/75_112_113_300_600_1444_1443curvefit_test10"

The emission lines that differ are HDELTA, HGAMMA, OIII_4363, and HBETA, and they usually differ around the third or fourth decimal place. 
OII_3727, OIII_4958, and OIII_5007 have the same values for the two dates.

**Comment by astrochun** [comment]
This is likely due to slight changes in the stellar absorption fitting for the Balmer lines and that OIII4363 is weak, so the fit can vary.
