### ISSUE TITLE
Implement Dust Attenuation

### ISSUE THREAD

**Issue by cmccormick1** [rafia37/Evolution-of-Galaxies#36]
On feature/dust_attenuation:
   
- [x] Implement E(B-V) calculation [9e80b9c]

- [x] Fix naming convention for error columns in `relation_fitting.extract_error_bars` (`lowhigh_error` --> `error`) [5ecd19c, 31a2f83]

- [x] Get rid of the call to MSC's `attenuation.EBV_table_update`. Now handled in `error_prop.fluxes_derived_prop` [3a7cd22]

- [x] Implement dust attenuation and error propagation using MSC's `error_prop.fluxes_derived_prop`. Test: 
     - [x] Raw data 
          - [x] Mass bins
          - [x] Mass-LHbeta bins
     - [x] Raw data, dust corrected
          - [x] Mass bins
          - [x] Mass-LHbeta bins
     - [x] MC, original validation table
          - [x] Mass bins
          - [x] Mass-LHbeta bins
     - [x] MC, revised validation table
          - [x] Mass bins
          - [x] Mass-LHbeta bins
     - [x] MC, dust corrected, revised validation table
          - [x] Mass bins
          - [x] Mass-LHbeta bins

**Comment by astrochun** [comment]
Will this issue include implementation of MSC's forthcoming feature of dust attenuation with error propagation?

**Comment by cmccormick1** [comment]
> Will this issue include implementation of MSC's forthcoming feature of dust attenuation with error propagation?

I think that's the plan for now. I may split it up later if it becomes too much for one issue.

**Comment by cmccormick1** [comment]
Leaving reorganization of function calls based off these changes for a further issue.
