### ISSUE TITLE
Integrate Metallicity_Stack_Commons in emission_line_fit

### ISSUE THREAD

**Issue by astrochun** [rafia37/Evolution-of-Galaxies#4]
Import `Metallicity_Stack_Commons.fitting` to retrieve:

1. `movingaverage_box1D()`
2. `gauss()`
3. `double_gauss()`
4. `oxy2_gauss()`
5. `rms_func()`
6. `con1`

**Comment by astrochun** [comment]
Changes implemented by @cmccormick1 in 66a5e23

**Comment by cmccormick1** [comment]
Testing Done:
1. Visual check of fitting and values on plots to make sure they are the same.
